routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/set_language/{lang}', 'Controller@setLanguage')->name('set_language');

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::get('/images/{path}/{attachment}', function ($path, $attachment){
   $file = sprintf('storage/%s/%s', $path, $attachment);
   if (File::exists($file)){
       return Image::make($file)->response();
   }
});

Route::group(['prefix' => 'courses'], function (){
    Route::get('/{course}/inscribe', 'CourseController@inscribe')
        ->name('course.inscribe')
        ->middleware('auth');
    Route::get('/{course}', 'CourseController@show')->name('courses.detail');
});

Route::group(['middleware' => ['auth']], function (){
    Route::group(['prefix' => 'subscriptions'], function (){
        Route::get('/plans', 'SubscriptionController@plans')->name('subscription.plans');
        Route::post('/process_subscription', 'SubscriptionController@processSubscription')->name('subscription.process_subscription');
        Route::get('/admin', 'SubscriptionController@admin')->name('subscriptions.admin');
        Route::post('/resume', 'SubscriptionController@resume')->name('subscriptions.resume');
        Route::post('/cancel', 'SubscriptionController@cancel')->name('subscriptions.cancel');

    });

    Route::group(['prefix' => 'invoices'], function (){
       Route::get('/admin', 'InvoiceController@admin')->name('invoices.admin');
       Route::get('/{invoice}/download', 'InvoiceController@download')->name('invoices.download');
    });
});

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Course;
use Illuminate\Http\Request;

class HomeController extends Controller
{


    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {

        $courses = Course::withCount(['student'])
            ->with('category', 'teacher', 'review')
            ->where('status', Course::PUBLISHED)
            ->latest()
            ->paginate(12);

        //dd($courses);

        return view('home', compact('courses'));
    }
}

resources/views/partials/courses/action_button.blade.php
<div class="col-3">
    @auth
        @can('opt_for_course', $course)
            @can('subscribe', \App\Course::class)
                <a class="btn btn-subscribe btn-bottom btn-block" href="{{ route('subscription.plans') }}">
                    <i class="fa fa-bolt"> {{ __("Subscribirme") }}</i>
                </a>
            @else
                @can('inscribe', $course)
                    <a class="btn btn-subscribe btn-bottom btn-block"
                       href="{{ route('course.inscribe', ['slug' => $course->slug]) }}"
                    >
                        <i class="fa fa-bolt"> {{ __("Inscribirme") }}</i>
                    </a>
                @else
                    <a class="btn btn-subscribe btn-bottom btn-block" href="#">
                        <i class="fa fa-bolt"> {{ __("Inscrito") }}</i>
                    </a>
                @endcan
            @endcan
        @else
            <a class="btn btn-subscribe btn-bottom btn-block" href="#">
                <i class="fa fa-user"> {{ __("Soy autor") }}</i>
            </a>
        @endcan
    @else
        <a class="btn btn-subscribe btn-bottom btn-block" href="{{ route('login') }}">
            <i class="fa fa-user"> {{ __("Acceder") }}</i>
        </a>
    @endauth
</div>

resources/views/partials/courses/card_course.blade.php
<div class="card card-01">
    <img
        class="card-img-top"
        src="{{ $course->pathAttachment() }}"
        alt="{{ $course->name }}"
    />
    <div class="card-body">
        <span class="badge-box"><i class="fa fa-check"></i> </span>
        <h4 class="card-title">{{ $course->name }}</h4>
        <hr/>
        <div class="row justify-content-center">
            @include('partials.courses.rating')
        </div>
        <hr/>
        <span class="badge badge-danger badge-cat">{{ $course->category->name }}</span>
        <p class="card-text">
            {{ str_limit($course->description, 100) }}
        </p>
        <a
            href="{{ route('courses.detail', $course->slug) }}"
            class="btn btn-course btn-block">
            {{ __("Más información") }}
        </a>
    </div>
</div>

resources/views/partials/courses/descriptions.blade.php
<div class="col-12 pt-0 mt-0">
    <h2 class="text-muted">{{ __("¿Que vamos a hacer?") }}</h2>
    <hr/>
</div>
<div class="col-12">
    <p class="mb-0">
        {{ $course->description }}
    </p>
</div>

resources/views/partials/courses/goals.blade.php
<div class="col-12 pt-0 mt-0">
    <h2 class="text-muted">{{ __("Metas del curso") }}</h2>
    <hr/>
</div>
@forelse($goals as $goal)
    <div class="col-6">
        <div class="card bg-light p-3">
            <p class="mb-0">
                {{ $goal->goal }}
            </p>
        </div>
    </div>
@empty
    <div class="alert alert-dark">
        <i class="fa fa-info-circle">
            {{ __("No se han escrito metas para este curso") }}
        </i>
    </div>
@endforelse

resources/views/partials/courses/jumbotron.blade.php
<div class="row">
    <div class="col-md-12">
        <div class="card pt-5" style="background-image: url('{{ url('/images/jumbotron.png') }}')">
            <div class="text-white text-center d-flex align-items-center py-5 px-4 my-5">
                <div class="col-4">
                    <img class="img-fluid" src="{{ $course->pathAttachment() }}"/>
                </div>

                <div class="col-5 text-left">
                    <h1>{{ __("Curso") }}: {{ $course->name }}</h1>
                    <h4>{{ __("Profesor") }}: {{ $course->teacher->user->name }}</h4>
                    <h5>{{ __("Categoria") }}: {{ $course->category->name }}</h5>
                    <h5>{{ __("Fecha de publicación") }}: {{ $course->created_at->format('d/m/Y') }}</h5>
                    <h5>{{ __("Fecha de actualización") }}: {{ $course->updated_at->format('d/m/Y') }}</h5>
                    <h6>{{ __("Estudiantes inscritos") }}: {{ $course->student_count }}</h6>
                    <h6>{{ __("N° de valoraciones") }}: {{ $course->review_count }}</h6>
                    @include('partials.courses.rating')
                </div>

                @include('partials.courses.action_button')
            </div>
        </div>
    </div>
</div>

resources/views/partials/courses/rating.blade.php
<div>
    <ul class="list-inline">
        <li class="list-inline-item"><i class="fa fa-star{{ $course->rating >=1 ? ' yellow' : '' }}"></i> </li>
        <li class="list-inline-item"><i class="fa fa-star{{ $course->rating >=2 ? ' yellow' : '' }}"></i> </li>
        <li class="list-inline-item"><i class="fa fa-star{{ $course->rating >=3 ? ' yellow' : '' }}"></i> </li>
        <li class="list-inline-item"><i class="fa fa-star{{ $course->rating >=4 ? ' yellow' : '' }}"></i> </li>
        <li class="list-inline-item"><i class="fa fa-star{{ $course->rating >=5 ? ' yellow' : '' }}"></i> </li>
    </ul>
</div>

resources/views/partials/courses/related.blade.php
<div class="col-12 pt-0 mt-4">
    <h2 class="text-muted">{{ __("Cursos similares") }}</h2>
    <hr/>
</div>
<div class="container-fluid">
    <div class="row">
        @forelse($related as $relatedCourse)
            <div class="col-md-6 listing-block">
                <div class="media">
                    <div class="fav-box">
                        <i class="far fa-heart"></i>
                    </div>
                    <a href="{{ route('courses.detail', $relatedCourse->slug) }}">
                        <img class="d-flex align-self-start"
                             src="/images/courses/{{ $relatedCourse->picture }}"
                             alt="{{ $relatedCourse->name }}"
                        />
                    </a>
                    <div class="media-body pl-3">
                        <div class="price">
                            <small>{{ $relatedCourse->name }}</small>
                        </div>

                        <div class="stats">
                            @include('partials.courses.rating', ['course' => $relatedCourse])
                        </div>
                    </div>
                </div>
            </div>
        @empty
            <div class="alert alert-dark">
                {{ __("No existe ningún curso relacionado") }}
            </div>
        @endforelse
    </div>
</div>

resources/views/partials/courses/requirement.blade.php
<div class="col-12 pt-0 mt-0">
    <h2 class="text-muted">{{ __("Requisitos para tomar el curso") }}</h2>
    <hr/>
</div>
@forelse($requirements as $requirement)
    <div class="col-6">
        <div class="card bg-light p-3">
            <p class="mb-0">
                {{ $requirement->requirement }}
            </p>
        </div>
    </div>
@empty
    <div class="alert alert-dark">
        <i class="fa fa-info-circle">
            {{ __("No hay ningún requisito para este curso") }}
        </i>
    </div>
@endforelse